def algo():
    print('POO Python')
    raise Exception('Toma Essa exceção')
    print('depois da excecao!')
    return 'sucesso' # ,- oque vem após o Raise nunca é executado
algo()
